### ISSUE TITLE
Build Fails on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by joesixpack** [ResistancePlatform/resistance-miner#14] opened 2019-08-13 22:18 UTC
sudo apt install build-essential pkg-config libcurl4-openssl-dev libssl-dev

[configure.log](https://github.com/ResistancePlatform/resistance-miner/files/3499102/configure.log)

[make.log](https://github.com/ResistancePlatform/resistance-miner/files/3499104/make.log)

**Comment by solardiz** [comment] 2019-08-14 10:22
Thanks for reporting. Assuming you did in fact install those packages, this looks like a regression introduced with the most recent update. (I now suspect that maybe the library name for linking against recent libcurl on Ubuntu is different than the `-lcurl` that this build tries to use.)

Can you please try the following:
```
git checkout 7a4af7e97bd086efeb91ec32b690965b42c5b0c9
make distclean
./autogen.sh
./configure
make | tee new-make.log
```

Does it help? If so, please provide `new-make.log` from this build.

**Comment by solardiz** [comment] 2019-08-14 12:48
I've reproduced the problem on Ubuntu 18.04.3 and came up with a workaround - turns out the `-lcurl` should be listed later on the `gcc` command line than it currently is. I'll plan on fixing the issue properly, with a commit to this repo.

**Comment by solardiz** [comment] 2019-08-14 16:19
I've just committed a fix for this issue. Please confirm that it works for you, and if so close the issue. Thanks!

**Comment by solardiz** [comment] 2019-08-16 09:06
I would have preferred to hear back from @joesixpack, but since per my own testing the issue is fixed I'll just assume that it in fact is.

**Closed by solardiz** 2019-08-16 09:06 UTC
